sudo: required
dist: trusty
language: java
services:
- docker
script: ant run
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t hello-world .
- docker push $DOCKER_USER/hello-world
